spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://43.201.188.96:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-secret: iVKKbgoepS
            client-id: cRB2fcyuQl_QRISKVV0a
            client-name: naver
          kakao:
            client-secret: unknown
            client-authentication-method: POST
            redirect-uri: http://43.201.188.96:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-id: 54a1a647665a4c69080a68825c0982a1
            scope: account_email
            client-name: kakao
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-secret: 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
            client-id: 505351076247-r4tihp3g0d6hdg9vrhqlk8bdfsnr93ck.apps.googleusercontent.com
            scope: email , profile
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
