server:
  port: 8080
client:
  url: http://43.201.239.102:3000

#logging
logging:
  level:
    org:
      hibernate:
        sql: debug
        type.descriptor.sql: trace
      springframework.web: debug
    jakarta: debug
spring:
  profiles:
    include: oauth
  servlet:
    multipart:
      max-request-size: 1MB
      max-file-size: 1MB

cloud:
  aws:
    s3:
      bucket: comma-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIA375CYUSRFNOT3HHO
      secretKey: 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