spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: http://15.165.85.78:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-secret: Qi1_grCX8U
            client-id: Ni5yEttxU_QaR3wb3pDA
            client-name: naver
          kakao:
            client-secret: unknown
            client-authentication-method: POST
            redirect-uri: http://15.165.85.78:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-id: 081b63daef05271b795420dfec1c2dd5
            scope: account_email
            client-name: kakao
          google:
            redirect-uri: http://15.165.85.78:8080/login/oauth2/code/google
            client-secret: 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
            client-id: 505351076247-r4tihp3g0d6hdg9vrhqlk8bdfsnr93ck.apps.googleusercontent.com
            scope: email , profile
        provider:
          kakao:
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
