spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comma?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
      platform: dev

#logging
logging:
  level:
    org:
      hibernate:
        sql: debug
        type.descriptor.sql: trace
      springframework.web: debug
    jakarta: debug
